[package]
name = "infrastructure"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
shared-kernel = { workspace = true }
ai-pipeline = { workspace = true }
context-engine = { workspace = true }
decision-engine = { workspace = true }
reflection-engine = { workspace = true }
memory-engine = { workspace = true }
object-store = { workspace = true }
store = { workspace = true }
event-store = { workspace = true }
signal-engine = { workspace = true }
vectorize = { workspace = true }
content-governance = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
