//! Daily Intelligence Brief endpoint.
//!
//! `GET /api/intelligence/briefing/today`
//!
//! The brief is generated by the scheduled cron handler (not on HTTP request).
//! Read path: KV cache → R2 Memory Archive → D1 legacy fallback.
//!
//! When no briefing has been generated yet, returns `{"status":"processing"}`.
//!
//! Error semantics:
//! - 200  Briefing found (from KV / R2 / D1)
//! - 200  No briefing yet (status: "processing")
//! - 503  Dependency failure (transient — may be generated next cycle)
//! - 500  Stored content corrupted (non-transient — investigate)

use crate::{fmt_date_ymd, json_err, json_err_internal, json_ok, param_i64, Store};
use object_store::{ObjectStore, R2Store};
use serde::Deserialize;
use worker::*;

/// KV cache TTL for today's briefing (24h — daily artifact is immutable).
const BRIEFING_CACHE_TTL_SEC: u64 = 86_400;

/// Envelope stored in the R2 Memory Archive for daily briefings.
#[derive(Deserialize)]
struct BriefingArtifactEnvelope {
    #[allow(dead_code)]
    schema_version: i32,
    #[allow(dead_code)]
    artifact_type: String,
    /// The inner briefing JSON.
    content: serde_json::Value,
}

/// Read today's briefing from the R2 Memory Archive.
async fn read_briefing_from_r2(env: &Env, date: &str) -> Option<serde_json::Value> {
    let bucket = env.bucket("RAW_CONTENT").ok()?;
    let store = R2Store::new(bucket);
    let key = object_store::keys::briefing(date);
    let bytes = store.read_object(&key).await.ok()??;
    let envelope: BriefingArtifactEnvelope = serde_json::from_slice(&bytes).ok()?;
    if envelope.schema_version != 1 || envelope.artifact_type != "daily_briefing" {
        console_log!("[briefing] r2_envelope_invalid date={} version={} type={}", date, envelope.schema_version, envelope.artifact_type);
        return None;
    }
    Some(envelope.content)
}

pub async fn today_briefing(_req: Request, ctx: RouteContext<()>) -> Result<Response> {
    let date = fmt_date_ymd((js_sys::Date::now() / 1000.0) as i64);
    let cache_key = format!("briefing:{date}");

    // 1. KV cache (fastest path)
    if let Some(cached) = crate::cache_get(&ctx.env, &cache_key).await {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&cached) {
            let mut resp = Response::from_json(&v)?;
            crate::cors_headers(&mut resp);
            return Ok(resp);
        }
    }

    // 2. KV miss — try R2 Memory Archive
    if let Some(briefing) = read_briefing_from_r2(&ctx.env, &date).await {
        if let Ok(json_str) = serde_json::to_string(&briefing) {
            crate::cache_put(&ctx.env, &cache_key, &json_str, BRIEFING_CACHE_TTL_SEC).await;
        }
        return json_ok(briefing);
    }

    // 3. R2 miss — D1 legacy fallback
    let store = match ctx.env.d1("DB") {
        Ok(db) => Store::new(db),
        Err(e) => {
            console_log!("[briefing] d1_binding_failed date={} error={:?}", date, e);
            return json_err(503, "Briefing temporarily unavailable");
        }
    };

    match store.load_today_briefing(&date).await {
        Ok(Some(content)) => match serde_json::from_str::<serde_json::Value>(&content) {
            Ok(briefing) => {
                if let Ok(json_str) = serde_json::to_string(&briefing) {
                    crate::cache_put(&ctx.env, &cache_key, &json_str, BRIEFING_CACHE_TTL_SEC).await;
                }
                json_ok(briefing)
            }
            Err(e) => {
                console_log!("[briefing] invalid_content date={} len={} error={}", date, content.len(), e);
                json_err(500, "Briefing content corrupted")
            }
        },
        Ok(None) => {
            // No briefing generated yet — return 200 with processing status
            json_ok(serde_json::json!({"status": "processing", "message": "Briefing is being generated."}))
        }
        Err(e) => {
            console_log!("[briefing] d1_load_failed date={} error={:?}", date, e);
            json_err(503, "Briefing temporarily unavailable")
        }
    }
}

/// GET /api/intelligence/briefings — list all historical briefings.
pub async fn list_briefings(_req: Request, ctx: RouteContext<()>) -> Result<Response> {
    let store = Store::new(ctx.env.d1("DB")?);
    match store.list_briefings().await {
        Ok(briefings) => json_ok(serde_json::json!({ "success": true, "briefings": briefings })),
        Err(e) => json_err_internal(&e.to_string()),
    }
}

/// GET /api/intelligence/briefings/:id — single historical briefing.
pub async fn get_briefing(_req: Request, ctx: RouteContext<()>) -> Result<Response> {
    let store = Store::new(ctx.env.d1("DB")?);
    let id = match param_i64(&ctx, "id") {
        Some(v) => v,
        None => return json_err(400, "invalid briefing id"),
    };
    match store.get_briefing_by_id(id).await {
        Ok(Some(content)) => match serde_json::from_str::<serde_json::Value>(&content) {
            Ok(briefing) => json_ok(briefing),
            Err(e) => json_err_internal(&e.to_string()),
        },
        Ok(None) => json_err(404, "briefing not found"),
        Err(e) => json_err_internal(&e.to_string()),
    }
}
