//! Daily Intelligence Brief endpoint.
//!
//! `GET /api/intelligence/briefing/today`
//!
//! The brief is generated by the scheduled cron handler (not on HTTP request).
//! This endpoint reads from the D1 `intelligence_briefs` table, with KV
//! caching for hot-read performance.
//!
//! When no briefing has been generated yet, returns HTTP 202 with
//! `{"status":"processing"}`.

use crate::{fmt_date_ymd, json_err, json_err_internal, json_ok, param_i64, Store};
use worker::*;

pub async fn today_briefing(_req: Request, ctx: RouteContext<()>) -> Result<Response> {
    let store = Store::new(ctx.env.d1("DB")?);
    let now = (js_sys::Date::now() / 1000.0) as i64;
    let date = fmt_date_ymd(now);

    // 1. Try KV cache
    let cache_key = format!("briefing:{date}");
    if let Some(cached) = crate::cache_get(&ctx.env, &cache_key).await {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&cached) {
            let mut resp = Response::from_json(&v)?;
            crate::cors_headers(&mut resp);
            return Ok(resp);
        }
    }

    // 2. KV miss — query D1
    match store.load_today_briefing(&date).await {
        Ok(Some(content)) => {
            // Parse the stored JSON content and return it
            match serde_json::from_str::<serde_json::Value>(&content) {
                Ok(briefing) => {
                    // Warm the cache (TTL: 6 hours)
                    if let Ok(json_str) = serde_json::to_string(&briefing) {
                        crate::cache_put(&ctx.env, &cache_key, &json_str, 360).await;
                    }
                    json_ok(briefing)
                }
                Err(e) => {
                    console_log!("[Sulix:briefing] parse stored content failed: {e}");
                    crate::json_err_internal("briefing content parse failed")
                }
            }
        }
        Ok(None) => {
            // No briefing generated yet — return 202 Accepted
            let mut resp = Response::error("processing", 202)?;
            crate::cors_headers(&mut resp);
            Ok(resp)
        }
        Err(e) => crate::json_err_internal(&e.to_string()),
    }
}

/// GET /api/intelligence/briefings — list all historical briefings.
pub async fn list_briefings(_req: Request, ctx: RouteContext<()>) -> Result<Response> {
    let store = Store::new(ctx.env.d1("DB")?);
    match store.list_briefings().await {
        Ok(briefings) => json_ok(serde_json::json!({ "success": true, "briefings": briefings })),
        Err(e) => json_err_internal(&e.to_string()),
    }
}

/// GET /api/intelligence/briefings/:id — single historical briefing.
pub async fn get_briefing(_req: Request, ctx: RouteContext<()>) -> Result<Response> {
    let store = Store::new(ctx.env.d1("DB")?);
    let id = match param_i64(&ctx, "id") {
        Some(v) => v,
        None => return json_err(400, "invalid briefing id"),
    };
    match store.get_briefing_by_id(id).await {
        Ok(Some(content)) => match serde_json::from_str::<serde_json::Value>(&content) {
            Ok(briefing) => json_ok(briefing),
            Err(e) => json_err_internal(&e.to_string()),
        },
        Ok(None) => json_err(404, "briefing not found"),
        Err(e) => json_err_internal(&e.to_string()),
    }
}
