//! Daily Intelligence Brief endpoints — composition-root owned.
//!
//! `GET /api/intelligence/briefing/today`
//! `GET /api/intelligence/briefings`
//! `GET /api/intelligence/briefings/:id`
//!
//! The brief is generated by the scheduled cron handler (not on HTTP request).
//! Read path: KV cache → R2 Memory Archive → D1 legacy fallback (application
//! `BriefingService`). Migrated from `api` in Phase 2 (Checkpoint F): the R2/KV
//! orchestration lives here in worker-entry; D1 persistence stays behind the
//! application service.
//!
//! Error semantics:
//! - 200  Briefing found (from KV / R2 / D1)
//! - 200  No briefing yet (status: "processing")
//! - 503  Dependency failure (transient — may be generated next cycle)
//! - 500  Stored content corrupted (non-transient — investigate)

use application::{BriefingService, ProductionAppServices};
use object_store::{ObjectStore, R2Store};
use serde::Deserialize;
use serde_json::json;
use worker::wasm_bindgen::JsValue;
use worker::*;

use super::response::{cors_headers, json_err, json_err_internal, json_ok};

/// KV cache TTL for today's briefing (24h — daily artifact is immutable).
const BRIEFING_CACHE_TTL_SEC: u64 = 86_400;

/// Envelope stored in the R2 Memory Archive for daily briefings.
#[derive(Deserialize)]
struct BriefingArtifactEnvelope {
    schema_version: i32,
    artifact_type: String,
    /// The inner briefing JSON.
    content: serde_json::Value,
}

async fn cache_get(env: &Env, key: &str) -> Option<String> {
    let kv = env.kv("CACHE").ok()?;
    kv.get(key).text().await.ok().flatten()
}

async fn cache_put(env: &Env, key: &str, value: &str, ttl: u64) {
    if let Ok(kv) = env.kv("CACHE") {
        if let Ok(builder) = kv.put(key, value) {
            let _ = builder.expiration_ttl(ttl).execute().await;
        }
    }
}

/// Format a unix timestamp (seconds) as YYYY-MM-DD using js_sys::Date.
fn fmt_date_ymd(ts_secs: i64) -> String {
    let d = js_sys::Date::new(&JsValue::from_f64((ts_secs as f64) * 1000.0));
    format!("{:04}-{:02}-{:02}", d.get_full_year(), d.get_month() + 1, d.get_date())
}

fn param_i64<D>(ctx: &RouteContext<D>, name: &str) -> Option<i64> {
    ctx.param(name)?.parse().ok()
}

/// Read today's briefing from the R2 Memory Archive.
async fn read_briefing_from_r2(env: &Env, date: &str) -> Option<serde_json::Value> {
    let bucket = env.bucket("RAW_CONTENT").ok()?;
    let store = R2Store::new(bucket);
    let key = object_store::keys::briefing(date);
    let bytes = store.read_object(&key).await.ok()??;
    let envelope: BriefingArtifactEnvelope = serde_json::from_slice(&bytes).ok()?;
    if envelope.schema_version != 1 || envelope.artifact_type != "daily_briefing" {
        console_log!(
            "[briefing] r2_envelope_invalid date={} version={} type={}",
            date,
            envelope.schema_version,
            envelope.artifact_type
        );
        return None;
    }
    Some(envelope.content)
}

pub(crate) async fn today_briefing(_req: Request, ctx: RouteContext<ProductionAppServices>) -> Result<Response> {
    let date = fmt_date_ymd((js_sys::Date::now() / 1000.0) as i64);
    let cache_key = format!("briefing:{date}");

    // 1. KV cache (fastest path)
    if let Some(cached) = cache_get(&ctx.env, &cache_key).await {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&cached) {
            let mut resp = Response::from_json(&v)?;
            cors_headers(&mut resp);
            return Ok(resp);
        }
    }

    // 2. KV miss — try R2 Memory Archive
    if let Some(briefing) = read_briefing_from_r2(&ctx.env, &date).await {
        if let Ok(json_str) = serde_json::to_string(&briefing) {
            cache_put(&ctx.env, &cache_key, &json_str, BRIEFING_CACHE_TTL_SEC).await;
        }
        return json_ok(briefing);
    }

    // 3. R2 miss — D1 legacy fallback (D1 read through BriefingService)
    let service = BriefingService::new(ctx.data.store.clone());

    match service.today(&date).await {
        Ok(Some(content)) => match serde_json::from_str::<serde_json::Value>(&content) {
            Ok(briefing) => {
                if let Ok(json_str) = serde_json::to_string(&briefing) {
                    cache_put(&ctx.env, &cache_key, &json_str, BRIEFING_CACHE_TTL_SEC).await;
                }
                json_ok(briefing)
            }
            Err(e) => {
                console_log!("[briefing] invalid_content date={} len={} error={}", date, content.len(), e);
                json_err(500, "Briefing content corrupted")
            }
        },
        Ok(None) => {
            // No briefing generated yet — return 200 with processing status
            json_ok(json!({"status": "processing", "message": "Briefing is being generated."}))
        }
        Err(e) => {
            console_log!("[briefing] d1_load_failed date={} error={:?}", date, e);
            json_err(503, "Briefing temporarily unavailable")
        }
    }
}

/// GET /api/intelligence/briefings — list all historical briefings.
pub(crate) async fn list_briefings(_req: Request, ctx: RouteContext<ProductionAppServices>) -> Result<Response> {
    let service = BriefingService::new(ctx.data.store.clone());
    match service.list().await {
        Ok(briefings) => json_ok(json!({ "success": true, "briefings": briefings })),
        Err(e) => json_err_internal(&e.to_string()),
    }
}

/// GET /api/intelligence/briefings/:id — single historical briefing.
pub(crate) async fn get_briefing(_req: Request, ctx: RouteContext<ProductionAppServices>) -> Result<Response> {
    let service = BriefingService::new(ctx.data.store.clone());
    let id = match param_i64(&ctx, "id") {
        Some(v) => v,
        None => return json_err(400, "invalid briefing id"),
    };
    match service.get(id).await {
        Ok(Some(content)) => match serde_json::from_str::<serde_json::Value>(&content) {
            Ok(briefing) => json_ok(briefing),
            Err(e) => json_err_internal(&e.to_string()),
        },
        Ok(None) => json_err(404, "briefing not found"),
        Err(e) => json_err_internal(&e.to_string()),
    }
}
