use anyhow::Result;

use super::helpers::html_escape;
use crate::engine::premium::PremiumReport;

/// 渲染 Premium 深度研报（长格式，多 Agent 合成）
pub fn render_premium_report(report: &PremiumReport) -> Result<String> {
    let risk_lines: String = report
        .risk_scenarios
        .iter()
        .map(|s| {
            format!(
                "<li class='text-neutral-700 text-sm mb-1'>{}</li>",
                html_escape(s)
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let sources_lines: String = report.sources.iter()
        .map(|s| format!("<span class='text-[10px] font-mono bg-neutral-100 text-neutral-600 px-1.5 py-0.5 rounded-sm border border-neutral-200/60'>{}</span>", html_escape(s)))
        .collect::<Vec<_>>()
        .join(" ");

    let html = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Premium Research — {} | Sulix Intel</title>
  <link rel="stylesheet" href="./design.css">
</head>
<body class="antialiased">
  <div class="h-[4px] w-full bg-[#e3120b]"></div>
  <div class="max-w-3xl mx-auto px-6 py-12">

    <div class="border-b-2 border-neutral-950 pb-6 mb-8">
      <span class="text-[#e3120b] text-xs font-bold uppercase tracking-widest">Premium Research</span>
      <h1 class="serif text-3xl sm:text-4xl font-bold mt-2 leading-tight">{}</h1>
      <div class="flex items-center gap-3 mt-3 text-xs text-neutral-400">
        <span>{}</span>
        <span>·</span>
        <span>Multi-Agent Intelligence Report</span>
      </div>
    </div>

    <div class="bg-white rounded-lg p-6 border border-neutral-200/80 mb-6">
      <h2 class="text-xs font-bold uppercase tracking-wider text-neutral-400 mb-3">Executive Summary</h2>
      <div class="text-neutral-800 text-[15px] leading-relaxed">{}</div>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
      <div class="bg-white rounded-lg p-5 border border-neutral-200/80">
        <span class="text-xs font-bold text-[#e3120b] uppercase tracking-wider">👤 Diplomat</span>
        <h3 class="text-sm font-semibold mt-1 mb-2">Geopolitical Assessment</h3>
        <p class="text-neutral-700 text-sm leading-relaxed">{}</p>
      </div>
      <div class="bg-white rounded-lg p-5 border border-neutral-200/80">
        <span class="text-xs font-bold text-amber-600 uppercase tracking-wider">👤 Architect</span>
        <h3 class="text-sm font-semibold mt-1 mb-2">Technical Impact</h3>
        <p class="text-neutral-700 text-sm leading-relaxed">{}</p>
      </div>
      <div class="bg-white rounded-lg p-5 border border-neutral-200/80">
        <span class="text-xs font-bold text-sky-700 uppercase tracking-wider">👤 Quant</span>
        <h3 class="text-sm font-semibold mt-1 mb-2">Commercial Framework</h3>
        <p class="text-neutral-700 text-sm leading-relaxed">{}</p>
      </div>
    </div>

    <div class="bg-white rounded-lg p-6 border border-neutral-200/80 mb-6">
      <h2 class="text-xs font-bold uppercase tracking-wider text-amber-700 mb-3">Risk Scenarios</h2>
      <ul class="space-y-1 list-disc pl-5">{}</ul>
    </div>

    <div class="border-t border-neutral-200 pt-4 mt-8">
      <h3 class="text-xs font-bold uppercase tracking-wider text-neutral-400 mb-2">Data Sources</h3>
      <div class="flex flex-wrap gap-1.5">{}</div>
    </div>

    <div class="mt-8 pt-4 border-t border-neutral-200">
      <p class="text-[10px] text-neutral-400 leading-relaxed">
        * Sulix Premium Research is generated by an automated multi-agent intelligence pipeline.
        Sources are cited for traceability. This is not financial or legal advice.
      </p>
    </div>

  </div>
</body>
</html>"#,
        html_escape(&report.theme_title),
        html_escape(&report.theme_title),
        html_escape(&report.date),
        html_escape(&report.executive_summary),
        html_escape(&report.geopolitical_assessment),
        html_escape(&report.technical_impact),
        html_escape(&report.commercial_framework),
        risk_lines,
        sources_lines,
    );

    Ok(html)
}
